src/auth/handler.js
src/index.js
src/source/handler.js
src/storage/bucket/list.js
src/utils/auth.js
src/utils/daCtx.js

Adds an auth check to all APIs.

Add Authentication

---

src/index.js

See above.
Some features broke.
Manually

Return 401 on unauthorized

---

.github/workflows/deploy-main.yaml
.github/workflows/run-tests.yaml
.gitignore
.nycrc.json
README.md
package-lock.json
package.json
src/utils/auth.js
src/utils/daCtx.js
test/utils/auth.test.js
test/utils/daCtx.test.js
test/utils/mocks/auth.js
test/utils/mocks/env.js
test/utils/mocks/fetch.js
test/utils/mocks/jose.js
test/utils/mocks/req.js

Significantly improves testing coverage.

Add test coverage

---

src/utils/auth.js
test/utils/auth.test.js
test/utils/mocks/req.js

When an anon user is present in a multi user auth it should not fail.

Add a test case for multi auth with anon user

---

src/utils/auth.js
test/utils/auth.test.js
test/utils/mocks/env.js

Emails in auth store are all lowercase, emails from Auth APi are not necessarily.

Auth Check should be case insensitive

---

src/storage/bucket/list.js
test/storage/bucket/list.test.js
test/storage/bucket/mocks/env.js

* All org permissions requested in parallel (map + promise.all)
* Tests!
Resolves: GH-50
E2E and Unit
I'm seeing responses no greater than 1s. This is down from 3s+ on cold starts.

GH-50 Org list performance

---

.nycrc.json
src/routes/source.js

Main branch no longer passes lint check.
Tests were run.

Fix lint issue from #69

---

package-lock.json
src/storage/object/list.js
src/storage/utils/list.js
test/storage/object/list.test.js

Add a `lastModified` attribute to the list object response.
#75 
As per request.
Added new tests to cover the expected response.

List Object - Add LastModified

---

src/storage/utils/list.js
test/it/get.spec.js
test/storage/object/list.test.js
test/storage/utils/list.test.js

Bring this branch up to date with API change.
#75 
Updated the tests.

Single Bucket - List Last Modified

---

src/handlers/unknown.js
src/index.js
test/handlers/unknown.test.js
test/index.test.js

Fix typo for `unknownHandler` and add some tests where that code was use.

fix(handlers): unknownHandler typo

---

src/storage/object/delete.js
test/storage/object/delete.test.js

Multiple concurrent versions on delete crosses the outgoing connection limit

Don't store version on delete

---

src/handlers/unknown.js
src/index.js
src/utils/daCtx.js
test/handlers/unknown.test.js
test/index.test.js

Incorporate #87 into Single Bucket.
Keep Single Bucket up-to-date with Main
Copied and updated tests

Fix Unknown Handler

---

src/utils/auth.js
test/utils/auth.test.js

Incorporate #94 into Single Bucket branch.
Included provided test cases.

Single Bucket - Multi-Sheet Auth Config support.

---

src/storage/object/list.js
src/storage/version/list.js
test/storage/object/list.test.js

* Limit version results to 500.
Resolves: GH-110
E2E
http://localhost:8787/versionlist/jmphlx/jmp-da/en/home.html <-- has over 1000 history entries
This is technically a breaking change, but I don't think it will impact anyone... 500 version entries should be plenty unless you're a healthcare company.
- [] My change requires a change to the documentation.

GH-110 - Limit version results

---

wrangler.toml

Need to add binding to DA Collab in prod.
None.
Due to need.

fix: Bind to DA Collab

---

src/routes/config.js
test/routes/config.test.js

Check read permission on config read
* Locally with da-live and da-collab
* Updated unit test

Check read permission for config reads

---

test/e2e/move.spec.js

Move tests limit should be more than 1
It's a test update.

chore: More Move Tests

---

src/routes/config.js
test/routes/config.test.js

Keep branches in sync.
Added tests.

feat: Add #117 to Adobe Infra

---

src/storage/version/put.js
test/storage/version/put.test.js

Revert "fix: versioning timestamp for version and document itself"

---

src/storage/object/get.js
src/utils/daResp.js
test/utils/daResp.test.js

Revert "fix: last modified header for source"

---

src/storage/utils/list.js
test/storage/utils/list.test.js

* List now matches the other functions that forcefully remove the key
* Org is handled outside of the key, made mocks match reality

chore: fix tests to match production
