src/index.js, src/utils/auth.js, src/utils/daCtx.js
Collab sessions can result in more than one user being responsible for a PUT - this PR makes it so that we da-admin allows more than one entry in the Authorization header and checks for all if the respective users is authorized. As a special case, it allows for an empty entry in the list of tokens which is interpreted as an anon user being present as well.
=> Allow for more than one user in Authorization

src/storage/bucket/list.js
The addition of more than one user in the authorization missed a spot in the list command where it did another check for the user. This fixes that.
=> Check for all users on list

.github/workflows/email-bot.yaml, src/handlers/get.js, src/routes/config.js, src/storage/kv/get.js, src/storage/kv/put.js, src/utils/daCtx.js, test/storage/kv/kv.test.js, wrangler.toml
* New `/config` route for GET & PUT methods
* Config API supports any key depth
* Added `fullKey` property to daCtx
* Added bindings for `DA_CONFIG` to prod, stage, and dev envs.
Resolves: GH-21
* New `/config` route for GET & PUT methods
* Config API supports any key depth
* Added fullKey property to daCtx
Resolves: [GH-21](https://github.com/adobe/da-admin/issues/21)
=> GH-21 - Config API

src/utils/daCtx.js, test/utils/daCtx.test.js, test/utils/mocks/req.js
* Support prefixing all routes with `/api`
Resolves: GH-24
1. Passing unit tests
2. Validated `da-admin` only uses pathname provided by daCtx.
=> GH-24 - Allow /api path prefix

.gitignore, src/handlers/patch.js, src/index.js, src/routes/version.js, src/storage/version/list.js, src/storage/version/patch.js, src/storage/version/put.js, src/utils/daResp.js, test/storage/version/patch.test.js
Make it possible to give a stored version a descriptive name. This can be done by sending a PATCH request to the version resource with as message body a JSON object with the `displayName`.
For example the PATCH request can be sent to the URL: `/versionsource/myorg/3246fe8b-3f32-481a-945a-786ee5a2133f/105ee238-c416-4371-896b-a16d1b0a4029.html` with data `{"displayName": "My Version"}`
#6 
* Tested locally with curl
* Tested in combination with da-live 
* Tested via unit tests
=> Support version naming

package-lock.json, package.json, src/helpers/source.js, src/storage/bucket/list.js, src/storage/object/put.js, src/utils/auth.js, test/helpers/source.test.js, test/storage/kv/kv.test.js, test/storage/object/mocks/version/put.js, test/storage/object/put.test.js, test/utils/mocks/env.js, test/utils/mocks/s3.js
* Ability to use `/config` to setup `admin.role.all`.
* Org performance improved by creating an `orgs` key (index) in DA_AUTH.
* Org / bucket check now only happens when org or repo is being POSTed. Middleware and index check / udpate will not be added if split path is longer than 2.
Resolves: GH-35
1. Visit: https://main--da-live--adobe.hlx.page/?da-admin=stage
2. Notice faster listing of orgs (down from 2s+ to < 1s)
3. Select a test org
4. Select config icon in breadcrumb
5. Add:
```
key            | value
admin.role.all | youremail@youremail.com
```
Notice that if you re-visit (with the stage query param) in a private window, the org will not be visible.
* Authentication is now self service using the config view.
* Org list performance improvements by creating an index. Cutting …
=> GH-35 - Self-service Authentication

src/handlers/post.js, src/helpers/rename.js, src/routes/rename.js, src/storage/object/rename.js
API to rename files and folders.
https://github.com/adobe/da-live/issues/96
- Tested locally with curl
- Tested in combination with da-live
1. Ability to rename files & folders.
2. Folder rename will perform a deep traversal to ensure all keys change.
=> GH-96 - Rename files and folders

src/handlers/post.js, src/routes/source.js, src/routes/version.js, src/storage/version/list.js, src/storage/version/patch.js, src/storage/version/put.js, test/storage/version/patch.test.js, test/storage/version/put.test.js
Make it possible to provide a version display name on the initial version POST/PUT.
#6
* Tested locally with da-collab and da-live
* Unit tests for all changes
1. Ability to add a label to a version upon creation.
Version labels provide a humane context to what a version represents. They can also be helpful for larger larger content projects. Changes happen over a series of days, weeks, or even months. This disjointed nature of content creation makes snapshot-style versions difficult to impossible to use. Being able to label versions provides a way to say in human terms, "rollback to a pre-Adobe MAX 2024 state."
DA Admin is built on top of object storage technologies. This provides a no-nonsense approach to data storage, but it lacks the granular nature of something like a NoSQL database. …
=> GH-6 Version Labels

package-lock.json, package.json, src/storage/object/put.js, src/storage/version/put.js, test/storage/version/put.test.js, wrangler.toml
In preparation for the parsing changes coming to da-collab https://github.com/adobe/da-collab/pull/38 and da-live https://github.com/adobe/da-collab/pull/38 store the content of a document automatically once.
#6 
Right now versions are only stored when a user explicitly requests this.
Locally with da-live and da-collab.
=> Store version content automatically once in preparation for parsing change

src/routes/source.js, src/storage/object/put.js, src/storage/version/put.js, test/routes/source.test.js, test/storage/version/put.test.js
Whenever a stored version is requested by the user, a new stored version is created, regardless of whether there already was a stored version with the same content.
Also cleaned up the da-admin -> da-collab communication to always use a service binding.
Fixes: #46 
* Locally with da-live and da-collab
* Unit tests
=>  Always create a new version when a version store is requested

.nycrc.json, package.json
Previously coverage figures were only on source files touched by unit tests, which meant that if you added tests to a previously untested sourcefile, it would typically bring the overall coverage down, unless that new file was immediately close to 100% covered. 
This change computes coverage figures on **_all_** source files, which is more truthful. 
It will seriously bring the coverage figure down, but the new coverage figure is the correct one.
Also updated `.nycrc.json` to accept the current figure as the minimum one.
A build system fix. No change to the actual product code.
=> Include coverage for all source files

src/routes/copy.js, src/storage/object/copy.js, src/storage/object/rename.js, test/storage/object/copy.test.js
When a resource is copied it should get a fresh version history.
The rename operation also uses the copy operation internally, in that case existing metadata is reused as before to preserve version history.
Fixes #56
* Tested locally with da-live and da-collab
* Unit tests for the changed code
* Playwright tests will be added soon too
=> Add new metadata for pure copies to get them a new version history

src/storage/object/copy.js
If a folder's' contents are being copied to a subfolder, and there are enough items to get to a continuation token, this will infinitely recurse to create content.
Fix a bug.
=> Fix Loop Bug

src/handlers/post.js, src/helpers/move.js, src/routes/move.js, src/storage/object/move.js
* Rename / Move is faster (more concurrent)
* Server-side API handles trying to rename / move a parent into a child.
* Server-side API handles trying to rename / move to the same location as the original source (add a timestamp)
* Rename / move is more reliable. If a file is moved, it should never exist anywhere else.
* Can reliably handle 10,000 documents in ~20s.
Resolves: GH-68
=> GH-68 - Move API

src/storage/object/copy.js, test/storage/object/copy.test.js
Check that source and destination of copy operation are not the same.
Fix #61 
Copy operations were causing loss of history if pasted to same directory.
Added unit tests.
=> Fix Copy Command Collisions

.eslintrc.cjs, src/routes/source.js, src/storage/object/delete.js, src/storage/object/move.js, src/storage/version/put.js, test/it/delete.spec.js, test/it/get.spec.js, test/it/head.spec.js, test/mocks/miniflare.js, test/routes/source.test.js, test/storage/object/delete.test.js
Next step in getting to a single bucket: delete object 
Added unit & integration tests.
=> Single Bucket - Delete object

.nycrc.json, package.json, src/helpers/copy.js, src/storage/object/copy.js, test/helpers/copy.test.js, test/it/post.spec.js, test/routes/copy.test.js, test/storage/object/copy.perf.js, test/storage/object/copy.test.js
Next step in getting to a single bucket: Copy & Rename operations
Added unit & integration tests.
=> Single Bucket - Copy/Rename

src/utils/auth.js, test/utils/auth.test.js
Org configuration can now be done in a single or multi sheet.
Fixes #93
Note that the sheet with the `admin` role configuration still needs to be called `data` as previously.
Locally with da-live/da-collab
Also added unit tests
=> Support org configuration with multiple sheets

.github/workflows/deploy-main.yaml, .github/workflows/install-lint-test.yaml, src/handlers/get.js, src/storage/object/copy.js, src/storage/object/list.js, src/storage/object/move.js, src/storage/object/put.js, src/storage/utils/config.js, src/storage/utils/list.js, src/storage/utils/version.js, src/storage/version/put.js, test/e2e/copy.spec.js, test/e2e/list.spec.js, test/e2e/move.spec.js, test/e2e/source.spec.js, test/e2e/version.spec.js, test/storage/object/copy.test.js, wrangler.toml
Adding some e2e tests against the API running in Cloudflare
Validating Single bucket operations. Fixing issues w/ bulk ops. Adding tests. 
To have confidence that future PRs will not break public facing API Use cases.
Added tests.
=> bug: Single Bucket Bulk Op Bugs & Tests

package-lock.json, package.json, src/utils/auth.js, test/utils/mocks/env.js, test/utils/mocks/jose.js, test/utils/offlineValidation.test.js
Validate IMS token
More tested added.
=> fix: More IMS Token validation

package-lock.json, package.json, src/utils/auth.js, test/utils/mocks/env.js, test/utils/mocks/jose.js, test/utils/offlineValidation.test.js, wrangler.toml
Add IMS offline token validation.
Unit tests only.
=> fix: add IMS offline token validation

README.md, src/helpers/source.js, src/storage/object/put.js, src/storage/version/put.js, src/utils/daResp.js, test/helpers/source.test.js, test/routes/source.test.js, test/storage/object/mocks/version/put.js, test/storage/object/put.test.js, test/storage/version/put.test.js, test/utils/daResp.test.js
The ID of the document can be provided on creation through the `guid` parameter as part of the Form Data. 
When requesting a document it's ID is reported via the `X-da-id` header in the response.
https://github.com/adobe/da-live/issues/378
* Added unit test
* Locally with da-live and da-collab
=> Allow document GUID to be provided as parameter on creation

src/storage/object/put.js
Remove a method from the code that's not used any more to fix the linter results.
Just a code cleanup. No logic changes.
=> chore(lint): remove unused method to fix lint result

src/utils/daResp.js, test/utils/daResp.test.js
Return `Last-Modified` response header for /source GET & HEAD requests.
fixes: #128
=> feat: return last modified for source based on timestamp

src/storage/object/get.js, src/utils/daResp.js, test/utils/daResp.test.js
Fix the last modified header for GET & HEAD /source, use the R2/S3 last modified date instead of the timestamp. This is now aligned with the /list API response as well https://github.com/adobe/da-admin/blob/a384662b6ecd9af80b3ad9ead5fa9b6763ebfcc2/src/storage/utils/list.js#L67
=> fix: last modified header for source

src/storage/utils/object.js, test/storage/utils/object.test.js
=> fix: only invalidate collab for html documents

src/storage/object/copy.js, src/storage/version/put.js, test/storage/version/put.test.js
Fixes: #169
Additional unit tests
=> fix: when catching exceptions don't rely on $metadata being set

src/storage/version/put.js, src/utils/constants.js, src/utils/daCtx.js, test/storage/version/put.test.js
There are rare cases when the document is emptied. We did not get to the root cause yet.
My proposal here: save the last version of the document before empty by adding a "Restore Point" labelled version with the document before it gets stored as empty. 
While this does not fix the initial problem, it will help authors to restore the document but it will also help us identify when this occurs exactly and potentially identify the root cause.
Appears like this in the UI:
=> feat: add a restore point if body is empty

src/storage/version/put.js
Need body sizes for better understanding
=> chore: fine tune logs

src/utils/auth.js, test/utils/auth.test.js
Fix https://github.com/adobe/da-admin/issues/175
This allows any request to `/versionsource` to pass the first step (basically = to "allow API to all"). Then API `getVersionSource` checks the document read access. If no read access to document, 403.
=> fix(versionsource): "delegate" permission check to api

src/storage/object/get.js
Write a log warning to track the documents that corrupted and used. Then I can run script to fix those.
=> chore: log gzip encoded content
